
---
- hosts: grp1
  become: true
  tasks:
   - name: copying the scripts
     copy: src=test.sh dest=/var/tmp/test.sh owner=root group=sys

   - name: executing the script
     shell: /var/tmp/test.sh


